<a href="https://colab.research.google.com/github/nur21horin/machine_learning/blob/main/Imbalance_Aware_Machine_Learning_for_Anomaly_Detection_in_Nuclear_Power_Plant_CPS_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
df=pd.read_csv("/content/Nuclear_Power_Plant_CPS_Dataset.csv")

In [18]:
df

,Timestamp,Reactor Temp (°C),Coolant Flow Rate (L/s),Pressure (MPa),Radiation Level (μSv/h),Turbine Speed (RPM),Pump Status,Power Output (MW),Control Rod Position (%),Steam Flow Rate (kg/s),Vibration Level (mm/s),Water Level (m),Anomaly Detected
0,2024-10-16 10:00:00,357.450712,471.878368,15.639131,0.352819,3301.404054,ON,978.518251,61.914141,220.491605,1.090474,5.077447,No
1,2024-10-16 10:01:00,347.926035,463.558917,16.088410,0.384267,3188.520927,ON,934.944537,71.731564,220.318340,2.934264,5.213480,No
2,2024-10-16 10:02:00,359.715328,471.834463,15.726660,1.214944,2920.910299,ON,978.550964,66.849758,205.981092,1.303091,5.198166,Yes
3,2024-10-16 10:03:00,372.845448,478.149470,15.864172,0.600205,3058.417812,ON,1048.238495,66.329191,221.163781,2.092060,5.188259,No
4,2024-10-16 10:04:00,346.487699,470.732901,16.836726,0.834639,3147.450650,OFF,1064.999369,62.767509,240.951403,2.034543,5.189138,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,2024-10-17 05:55:00,356.607121,448.255322,16.573220,0.220798,3234.293864,OFF,1091.628062,74.358513,232.233914,1.903697,5.199113,No
1196,2024-10-17 05:56:00,349.705433,456.172103,15.513311,0.745855,3430.529621,ON,923.486043,72.547568,195.655376,1.613583,5.313369,No
1197,2024-10-17 05:57:00,358.287349,454.940639,16.503567,0.015188,2956.519241,OFF,993.878201,69.063348,201.798050,1.943002,5.067517,No
1198,2024-10-17 05:58:00,353.358712,473.109010,16.168072,-0.015107,3293.590084,ON,954.574874,76.957290,236.462275,1.830008,5.296526,No
1199,2024-10-17 05:59:00,370.462106,471.040165,15.886262,0.821754,2965.943859,ON,1030.205373,68.938778,202.420991,2.976472,5.272099,No

In [19]:
df.shape

(1200, 13)

In [20]:
df.describe()

,Reactor Temp (°C),Coolant Flow Rate (L/s),Pressure (MPa),Radiation Level (μSv/h),Turbine Speed (RPM),Power Output (MW),Control Rod Position (%),Steam Flow Rate (kg/s),Vibration Level (mm/s),Water Level (m)
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,350.575733,470.369775,16.008382,0.581900,3192.985499,1000.442858,70.123696,219.841024,1.990574,5.198914
std,14.825930,14.756203,0.511526,0.295586,201.808719,52.127700,4.996608,14.363382,0.500757,0.098022
min,301.380990,424.707318,14.504432,-0.353011,2620.097224,815.581735,50.816722,161.163996,0.312210,4.896601
25%,340.624931,460.370079,15.646462,0.386899,3061.261439,965.441255,66.845331,210.077114,1.661971,5.135156
50%,350.724549,470.184693,16.008505,0.593313,3192.707942,999.437283,70.100292,220.139668,1.975637,5.199864
75%,360.140211,480.089684,16.346386,0.777762,3326.666520,1036.376938,73.409052,229.360633,2.318087,5.264305
max,407.790972,517.896614,17.963119,1.572928,3822.582040,1155.884056,86.886915,263.711638,3.688884,5.528412

In [21]:
df.head()

,Timestamp,Reactor Temp (°C),Coolant Flow Rate (L/s),Pressure (MPa),Radiation Level (μSv/h),Turbine Speed (RPM),Pump Status,Power Output (MW),Control Rod Position (%),Steam Flow Rate (kg/s),Vibration Level (mm/s),Water Level (m),Anomaly Detected
0,2024-10-16 10:00:00,357.450712,471.878368,15.639131,0.352819,3301.404054,ON,978.518251,61.914141,220.491605,1.090474,5.077447,No
1,2024-10-16 10:01:00,347.926035,463.558917,16.088410,0.384267,3188.520927,ON,934.944537,71.731564,220.318340,2.934264,5.213480,No
2,2024-10-16 10:02:00,359.715328,471.834463,15.726660,1.214944,2920.910299,ON,978.550964,66.849758,205.981092,1.303091,5.198166,Yes
3,2024-10-16 10:03:00,372.845448,478.149470,15.864172,0.600205,3058.417812,ON,1048.238495,66.329191,221.163781,2.092060,5.188259,No
4,2024-10-16 10:04:00,346.487699,470.732901,16.836726,0.834639,3147.450650,OFF,1064.999369,62.767509,240.951403,2.034543,5.189138,No

In [22]:
df['Timestamp']=pd.to_datetime(df['Timestamp'])

In [23]:
df.head()

,Timestamp,Reactor Temp (°C),Coolant Flow Rate (L/s),Pressure (MPa),Radiation Level (μSv/h),Turbine Speed (RPM),Pump Status,Power Output (MW),Control Rod Position (%),Steam Flow Rate (kg/s),Vibration Level (mm/s),Water Level (m),Anomaly Detected
0,2024-10-16 10:00:00,357.450712,471.878368,15.639131,0.352819,3301.404054,ON,978.518251,61.914141,220.491605,1.090474,5.077447,No
1,2024-10-16 10:01:00,347.926035,463.558917,16.088410,0.384267,3188.520927,ON,934.944537,71.731564,220.318340,2.934264,5.213480,No
2,2024-10-16 10:02:00,359.715328,471.834463,15.726660,1.214944,2920.910299,ON,978.550964,66.849758,205.981092,1.303091,5.198166,Yes
3,2024-10-16 10:03:00,372.845448,478.149470,15.864172,0.600205,3058.417812,ON,1048.238495,66.329191,221.163781,2.092060,5.188259,No
4,2024-10-16 10:04:00,346.487699,470.732901,16.836726,0.834639,3147.450650,OFF,1064.999369,62.767509,240.951403,2.034543,5.189138,No

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Timestamp                 1200 non-null   datetime64[ns]
 1   Reactor Temp (°C)         1200 non-null   float64
 2   Coolant Flow Rate (L/s)   1200 non-null   float64
 3   Pressure (MPa)            1200 non-null   float64
 4   Radiation Level (μSv/h)   1200 non-null   float64
 5   Turbine Speed (RPM)       1200 non-null   float64
 6   Pump Status               1200 non-null   object
 7   Power Output (MW)         1200 non-null   float64
 8   Control Rod Position (%)  1200 non-null   float64
 9   Steam Flow Rate (kg/s)    1200 non-null   float64
 10  Vibration Level (mm/s)    1200 non-null   float64
 11  Water Level (m)           1200 non-null   float64
 12  Anomaly Detected          1200 non-null   object
dtypes: datetime64[ns](1), float64(10), object(2)
memory usage: 122.0+ KB

In [25]:
df.describe()

,Timestamp,Reactor Temp (°C),Coolant Flow Rate (L/s),Pressure (MPa),Radiation Level (μSv/h),Turbine Speed (RPM),Power Output (MW),Control Rod Position (%),Steam Flow Rate (kg/s),Vibration Level (mm/s),Water Level (m)
count,1200,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,2024-10-16 19:59:30,350.575733,470.369775,16.008382,0.581900,3192.985499,1000.442858,70.123696,219.841024,1.990574,5.198914
min,2024-10-16 10:00:00,301.380990,424.707318,14.504432,-0.353011,2620.097224,815.581735,50.816722,161.163996,0.312210,4.896601
25%,2024-10-16 14:59:45,340.624931,460.370079,15.646462,0.386899,3061.261439,965.441255,66.845331,210.077114,1.661971,5.135156
50%,2024-10-16 19:59:30,350.724549,470.184693,16.008505,0.593313,3192.707942,999.437283,70.100292,220.139668,1.975637,5.199864
75%,2024-10-17 00:59:15,360.140211,480.089684,16.346386,0.777762,3326.666520,1036.376938,73.409052,229.360633,2.318087,5.264305
max,2024-10-17 05:59:00,407.790972,517.896614,17.963119,1.572928,3822.582040,1155.884056,86.886915,263.711638,3.688884,5.528412
std,NaN,14.825930,14.756203,0.511526,0.295586,201.808719,52.127700,4.996608,14.363382,0.500757,0.098022

In [27]:
train_size=int(0.8*len(df))
val_size=int(0.1*len(df))
train=df.iloc[:train_size]
val=df.iloc[train_size:train_size+val_size]
test=df.iloc[train_size+val_size:]

## Feature Engineering

In [28]:
# Extract time-based features from 'Timestamp'
df['hour'] = df['Timestamp'].dt.hour
df['dayofweek'] = df['Timestamp'].dt.dayofweek
df['dayofmonth'] = df['Timestamp'].dt.day
df['month'] = df['Timestamp'].dt.month
df['year'] = df['Timestamp'].dt.year
df['weekofyear'] = df['Timestamp'].dt.isocalendar().week.astype(int)
df['is_weekend'] = (df['Timestamp'].dt.dayofweek >= 5).astype(int)
df['is_month_start'] = df['Timestamp'].dt.is_month_start.astype(int)
df['is_month_end'] = df['Timestamp'].dt.is_month_end.astype(int)
df['is_quarter_start'] = df['Timestamp'].dt.is_quarter_start.astype(int)
df['is_quarter_end'] = df['Timestamp'].dt.is_quarter_end.astype(int)
df['is_year_start'] = df['Timestamp'].dt.is_year_start.astype(int)
df['is_year_end'] = df['Timestamp'].dt.is_year_end.astype(int)

display(df.head())

,Timestamp,Reactor Temp (°C),Coolant Flow Rate (L/s),Pressure (MPa),Radiation Level (μSv/h),Turbine Speed (RPM),Pump Status,Power Output (MW),Control Rod Position (%),Steam Flow Rate (kg/s),...,month,year,weekofyear,is_weekend,is_month_start,is_month_end,is_quarter_start,is_quarter_end,is_year_start,is_year_end
0,2024-10-16 10:00:00,357.450712,471.878368,15.639131,0.352819,3301.404054,ON,978.518251,61.914141,220.491605,...,10,2024,42,0,0,0,0,0,0,0
1,2024-10-16 10:01:00,347.926035,463.558917,16.088410,0.384267,3188.520927,ON,934.944537,71.731564,220.318340,...,10,2024,42,0,0,0,0,0,0,0
2,2024-10-16 10:02:00,359.715328,471.834463,15.726660,1.214944,2920.910299,ON,978.550964,66.849758,205.981092,...,10,2024,42,0,0,0,0,0,0,0
3,2024-10-16 10:03:00,372.845448,478.149470,15.864172,0.600205,3058.417812,ON,1048.238495,66.329191,221.163781,...,10,2024,42,0,0,0,0,0,0,0
4,2024-10-16 10:04:00,346.487699,470.732901,16.836726,0.834639,3147.450650,OFF,1064.999369,62.767509,240.951403,...,10,2024,42,0,0,0,0,0,0,0

### Encoding Categorical Features

We need to convert the categorical columns ('Pump Status' and 'Anomaly Detected') into a numerical format that machine learning models can understand.

*   **'Pump Status'**: This is a nominal categorical variable (ON/OFF). One-hot encoding is suitable here to avoid implying any ordinal relationship.
*   **'Anomaly Detected'**: This is a binary target variable ('Yes'/'No'). We can map 'Yes' to 1 and 'No' to 0.

In [29]:
# One-hot encode 'Pump Status'
df = pd.get_dummies(df, columns=['Pump Status'], drop_first=True)

# Map 'Anomaly Detected' to numerical (0 and 1)
df['Anomaly Detected'] = df['Anomaly Detected'].map({'Yes': 1, 'No': 0})

# Display the head and info of the DataFrame to see the changes
display(df.head())
display(df.info())

,Timestamp,Reactor Temp (°C),Coolant Flow Rate (L/s),Pressure (MPa),Radiation Level (μSv/h),Turbine Speed (RPM),Power Output (MW),Control Rod Position (%),Steam Flow Rate (kg/s),Vibration Level (mm/s),...,year,weekofyear,is_weekend,is_month_start,is_month_end,is_quarter_start,is_quarter_end,is_year_start,is_year_end,Pump Status_ON
0,2024-10-16 10:00:00,357.450712,471.878368,15.639131,0.352819,3301.404054,978.518251,61.914141,220.491605,1.090474,...,2024,42,0,0,0,0,0,0,0,True
1,2024-10-16 10:01:00,347.926035,463.558917,16.088410,0.384267,3188.520927,934.944537,71.731564,220.318340,2.934264,...,2024,42,0,0,0,0,0,0,0,True
2,2024-10-16 10:02:00,359.715328,471.834463,15.726660,1.214944,2920.910299,978.550964,66.849758,205.981092,1.303091,...,2024,42,0,0,0,0,0,0,0,True
3,2024-10-16 10:03:00,372.845448,478.149470,15.864172,0.600205,3058.417812,1048.238495,66.329191,221.163781,2.092060,...,2024,42,0,0,0,0,0,0,0,True
4,2024-10-16 10:04:00,346.487699,470.732901,16.836726,0.834639,3147.450650,1064.999369,62.767509,240.951403,2.034543,...,2024,42,0,0,0,0,0,0,0,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Timestamp                 1200 non-null   datetime64[ns]
 1   Reactor Temp (°C)         1200 non-null   float64
 2   Coolant Flow Rate (L/s)   1200 non-null   float64
 3   Pressure (MPa)            1200 non-null   float64
 4   Radiation Level (μSv/h)   1200 non-null   float64
 5   Turbine Speed (RPM)       1200 non-null   float64
 6   Power Output (MW)         1200 non-null   float64
 7   Control Rod Position (%)  1200 non-null   float64
 8   Steam Flow Rate (kg/s)    1200 non-null   float64
 9   Vibration Level (mm/s)    1200 non-null   float64
 10  Water Level (m)           1200 non-null   float64
 11  Anomaly Detected          1200 non-null   int64
 12  hour                      1200 non-null   int32
 13  dayofweek                 1200 non-null   int32
 14  dayofmonth                1200 non-null   int32
 15  month                     1200 non-null   int32
 16  year                      1200 non-null   int32
 17  weekofyear                1200 non-null   int64
 18  is_weekend                1200 non-null   int64
 19  is_month_start            1200 non-null   int64
 20  is_month_end              1200 non-null   int64
 21  is_quarter_start          1200 non-null   int64
 22  is_quarter_end            1200 non-null   int64
 23  is_year_start             1200 non-null   int64
 24  is_year_end               1200 non-null   int64
 25  Pump Status_ON            1200 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(10), int32(5), int64(9)
memory usage: 212.2 KB

None

In [31]:
df.isnull().sum()

Timestamp                   0
Reactor Temp (°C)           0
Coolant Flow Rate (L/s)     0
Pressure (MPa)              0
Radiation Level (μSv/h)     0
Turbine Speed (RPM)         0
Power Output (MW)           0
Control Rod Position (%)    0
Steam Flow Rate (kg/s)      0
Vibration Level (mm/s)      0
Water Level (m)             0
Anomaly Detected            0
hour                        0
dayofweek                   0
dayofmonth                  0
month                       0
year                        0
weekofyear                  0
is_weekend                  0
is_month_start              0
is_month_end                0
is_quarter_start            0
is_quarter_end              0
is_year_start               0
is_year_end                 0
Pump Status_ON              0
dtype: int64

## Data Preparation for Modeling: SMOTE and Class Weighting

To prepare the data for modeling, especially for imbalanced datasets, we will combine SMOTE (Synthetic Minority Oversampling Technique) with cost-sensitive learning through class weights.

First, we need to re-split the `df` DataFrame into `train`, `val`, and `test` sets to ensure that all engineered features and encoded columns are present in these subsets. Then, we will apply SMOTE to the training data to balance the classes and calculate class weights for use in the model.

In [32]:
# Re-split data to include all engineered features and encoded columns
train_size = int(0.8 * len(df))
val_size = int(0.1 * len(df))

train_df = df.iloc[:train_size].copy()
val_df = df.iloc[train_size : train_size + val_size].copy()
test_df = df.iloc[train_size + val_size :].copy()

print(f"Original training set shape: {train_df.shape}")
print(f"Original validation set shape: {val_df.shape}")
print(f"Original test set shape: {test_df.shape}")

Original training set shape: (960, 26)
Original validation set shape: (120, 26)
Original test set shape: (120, 26)

### Separate Features and Target

Now, let's define our features (X) and the target variable (y) for the training, validation, and test sets. We'll drop the 'Timestamp' column as its information has been captured in the extracted time-based features, and the 'Anomaly Detected' column is our target.

In [33]:
# Define features (X) and target (y)
TARGET_COLUMN = 'Anomaly Detected'
FEATURES = [col for col in df.columns if col not in ['Timestamp', TARGET_COLUMN]]

X_train = train_df[FEATURES]
y_train = train_df[TARGET_COLUMN]

X_val = val_df[FEATURES]
y_val = val_df[TARGET_COLUMN]

X_test = test_df[FEATURES]
y_test = test_df[TARGET_COLUMN]

print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}, y_val shape: {y_val.shape}")
print(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")

# Check initial class distribution in y_train
print("\nInitial class distribution in training data (y_train):")
display(y_train.value_counts())

X_train shape: (960, 24), y_train shape: (960,)
X_val shape: (120, 24), y_val shape: (120,)
X_test shape: (120, 24), y_test shape: (120,)

Initial class distribution in training data (y_train):

Anomaly Detected
0    909
1     51
Name: count, dtype: int64

### Apply SMOTE to Training Data

We will use SMOTE to oversample the minority class ('Anomaly Detected' = 1) in the training data to address the class imbalance. Based on the request, we will aim for a specific ratio (e.g., 1:2 for minority to majority).

In [34]:
from imblearn.over_sampling import SMOTE

# Instantiate SMOTE
# Calculate the current ratio of minority (1) to majority (0)
minority_count = y_train.value_counts()[1]
majority_count = y_train.value_counts()[0]

# Target a 1:2 ratio (minority:majority)
sampling_strategy_ratio = {0: majority_count, 1: int(majority_count / 2)}

sm = SMOTE(sampling_strategy=sampling_strategy_ratio, random_state=42)

# Apply SMOTE only to the training data
X_train_resampled, y_train_resampled = sm.fit_resample(X_train, y_train)

print("\nClass distribution after SMOTE:")
display(y_train_resampled.value_counts())
print(f"Resampled X_train shape: {X_train_resampled.shape}, resampled y_train shape: {y_train_resampled.shape}")

Class distribution after SMOTE:

Anomaly Detected
0    909
1    454
Name: count, dtype: int64

Resampled X_train shape: (1363, 24), resampled y_train shape: (1363,)

### Calculate Class Weights

To further address the imbalance and introduce cost-sensitive learning, we will calculate class weights. These weights can be passed to many machine learning models to give more importance to the minority class during training. We calculate these weights based on the *resampled* training data.

In [35]:
from sklearn.utils import class_weight

# Calculate class weights for the resampled data
class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_resampled),
    y=y_train_resampled
)

# Convert to a dictionary for easier use in models
class_weights_dict = dict(zip(np.unique(y_train_resampled), class_weights))

print("Class weights:")
print(class_weights_dict)

Class weights:
{np.int64(0): np.float64(0.7497249724972497), np.int64(1): np.float64(1.501101321585903)}

## Model Training and Evaluation

Now that the data is prepared, let's train different classification models. We will evaluate each model on both the original (imbalanced) training data and the SMOTE-resampled training data to understand the impact of balancing techniques. We'll use the validation set (`X_val`, `y_val`) for evaluation.

### 1. Random Forest Classifier

We will train a Random Forest Classifier using `class_weight='balanced'` to handle class imbalance, first on the original training data and then on the SMOTE-resampled data.

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report, confusion_matrix

def train_evaluate_model(model, X_train_data, y_train_data, X_val, y_val, model_name, data_source):
    """Trains and evaluates a given model."""
    print(f"\n--- Training {model_name} on {data_source} Data ---")

    # Train the model
    model.fit(X_train_data, y_train_data)

    # Make predictions on the validation set
    y_pred = model.predict(X_val)
    y_proba = model.predict_proba(X_val)[:, 1] # Probability of the positive class

    # Evaluate the model
    print(f"\n{model_name} - {data_source} Evaluation on Validation Set:")
    print(f"Accuracy: {accuracy_score(y_val, y_pred):.4f}")
    print(f"Precision: {precision_score(y_val, y_pred):.4f}")
    print(f"Recall: {recall_score(y_val, y_pred):.4f}")
    print(f"F1-Score: {f1_score(y_val, y_pred):.4f}")
    print(f"ROC AUC Score: {roc_auc_score(y_val, y_proba):.4f}")
    print("\nClassification Report:")
    print(classification_report(y_val, y_pred))
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_val, y_pred))

# -----------------------------------------------------------------------------
# 1. Random Forest Classifier on Original Imbalanced Data
print("\n### Random Forest on Original Data")
rf_model_original = RandomForestClassifier(random_state=42, class_weight='balanced')
train_evaluate_model(rf_model_original, X_train, y_train, X_val, y_val, 'Random Forest', 'Original')

# -----------------------------------------------------------------------------
# 2. Random Forest Classifier on SMOTE-Resampled Data
print("\n### Random Forest on SMOTE-Resampled Data")
rf_model_smote = RandomForestClassifier(random_state=42, class_weight='balanced')
train_evaluate_model(rf_model_smote, X_train_resampled, y_train_resampled, X_val, y_val, 'Random Forest', 'SMOTE-Resampled')

### Random Forest on Original Data

--- Training Random Forest on Original Data ---

Random Forest - Original Evaluation on Validation Set:
Accuracy: 0.9333
Precision: 0.0000
Recall: 0.0000
F1-Score: 0.0000
ROC AUC Score: 0.5257

Classification Report:
              precision    recall  f1-score   support

           0       0.93      1.00      0.97       112
           1       0.00      0.00      0.00         8

    accuracy                           0.93       120
   macro avg       0.47      0.50      0.48       120
weighted avg       0.87      0.93      0.90       120


Confusion Matrix:
[[112   0]
 [  8   0]]

### Random Forest on SMOTE-Resampled Data

--- Training Random Forest on SMOTE-Resampled Data ---

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Random Forest - SMOTE-Resampled Evaluation on Validation Set:
Accuracy: 0.9333
Precision: 0.0000
Recall: 0.0000
F1-Score: 0.0000
ROC AUC Score: 0.2952

Classification Report:
              precision    recall  f1-score   support

           0       0.93      1.00      0.97       112
           1       0.00      0.00      0.00         8

    accuracy                           0.93       120
   macro avg       0.47      0.50      0.48       120
weighted avg       0.87      0.93      0.90       120


Confusion Matrix:
[[112   0]
 [  8   0]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))